service: web-app # NOTE: update this with your service name

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10

functions:
  createNewPost:
    handler: src/postsController.createNewPost
    events:
      - http:
          path: /posts/new
          method: post
          cors: true
  register:
    handler: src/authenticationController.register
    events:
      - http:
          path: /register
          method: post
          cors: true
  login:
    handler: src/authenticationController.login
    events:
      - http:
          path: /login
          method: post
          cors: true
  findPostById:
    handler: src/postsController.findPostById
    events:
      - http:
          path: /posts/{id}
          method: get
          cors: true
  findUserById:
    handler: src/usersController.findUserById
    events:
      - http:
          path: /users/{id}
          method: get
          cors: true
  showPageOfPosts:
    handler: src/postsController.showPageOfPosts
    events:
      - http:
          path: /page/{number}
          method: get
          cors: true
  saveNote:
    handler: src/notesController.saveNote
    events:
      - http:
          path: /notes/save
          method: post
          cors: true
  deleteNote:
    handler: src/notesController.deleteNote
    events:
      - http:
          path: /notes/delete/{number}
          method: get
          cors: true
  updateUserInfo:
    handler: src/usersController.updateUserInfo
    events:
      - http:
          path: /users/update
          method: put
          cors: true
