service: web-app # NOTE: update this with your service name

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get
  createNewPost:
    handler: handler.createNewPost
    events:
      - http:
          path: /posts/new
          method: post
          cors: true
  register:
    handler: handler.register
    events:
      - http:
          path: /register
          method: post
          cors: true
  login:
    handler: handler.login
    events:
      - http:
          path: /login
          method: post
          cors: true
  findPostById:
    handler: handler.findPostById
    events:
      - http:
          path: /posts/{id}
          method: get
  findUserById:
    handler: handler.findUserById
    events:
      - http:
          path: /users/{id}
          method: get
  showPageOfPosts:
    handler: handler.showPageOfPosts
    events:
      - http:
          path: /page/{number}
          method: get
